---
# MHelpModifer's default config

# Messages will be shown when doing /help:
messages:
  - "&l&aHello, {name}!"
  - "Do /list to see who are the players online!"
  - "There are {playercount} players online!"
  - "You are currently in Level &3{playerlevel}"
  - "In &7{playerlevel}&f are &9{playerlevelcount} &fplayers!"
  - "Did you know that you can now add unlimited pages?"
  - "No? Well, then give it a shot now!"
  - "It's as simple as changing the config!"
  - "&eHave &afun &eon our Server&6!"
...
