---
# MHelpModifer's default config

# Messages will be shown when doing /help:
messages:
  - "&l&aHello, {name}!"
  - "Do /list to see who are the players online!"
  - "There are {playercount} players online!"
  - "You are currently in Level &3{playerlevel}"
  - "In &7{playerlevel}&f are &9{playerlevelcount} &fplayers!"
  - "Did you know that you can add now unlimited pages?"
  - "No? Then try now!"
  - "Just change the config"
  - "&eHave &afun &eon our Server&6!"
...
